version: 2.1

orbs:
  slack: circleci/slack@4.9.3

workflows:
  test-deploy:
    jobs:
      - test:
          context:
            - slack-ci
      - extract-e2e-results:
          requires:
            - test
      - send-e2e-results:
          requires:
            - extract-e2e-results
  genereate-e2e-report:
    triggers:
      - schedule:
          cron: "17 8 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test:
          context:
            - slack-ci
      - extract-e2e-results:
          requires:
            - test
      - send-e2e-results:
          requires:
            - extract-e2e-results
commands:
  e2e_test:
    steps:
      - checkout
      # - run:
      #     working_directory: crx/src
      #     name: Install crx deps
      #     command: npm install
      # - run:
      #     working_directory: crx/src
      #     name: Prepare crx
      #     command: npm run prod
      - run:
          working_directory: e2e
          name: Install dependencies
          command: npm install
      - run:
          working_directory: e2e
          name: Setup playwright
          command: npx playwright install
      - run:
          working_directory: e2e
          name: Run e2e
          command: npx playwright test

      - store_artifacts:
          path: e2e/playwright-report
          destination: playwright-report

  extract-e2e-results:
    steps:
      - run:
          name: Install jq
          command: apt-get update && apt-get install -y jq
      - run:
          working_directory: e2e
          name: Extract stats for notification
          command: |
            STATS=$(jq -r '[.stats.expected // 0, .stats.unexpected // 0, .status.flaky // 0, .stats.skipped // 0] | @tsv' test-results.json)
            read -r PASSED_TESTS FAILED_TESTS FLAKY_TESTS SKIPPED_TESTS \<<< "$STATS"
            echo "PASSED_TESTS=$PASSED_TESTS, FAILED_TESTS=$FAILED_TESTS, FLAKY_TESTS=$FLAKY_TESTS, SKIPPED_TESTS=$SKIPPED_TESTS"
                  if [ "$FAILED_TESTS" -gt 0 ]; then
                        STATUS_MESSAGE=":x:"
                  else
                        STATUS_MESSAGE=":white_check_mark:"
                  fi
            echo "export STATUS_MESSAGE=$STATUS_MESSAGE
                  export PASSED_TESTS=$PASSED_TESTS
                  export FAILED_TESTS=$FAILED_TESTS
                  export FLAKY_TESTS=$FLAKY_TESTS
                  export SKIPPED_TESTS=$SKIPPED_TESTS" >> $BASH_ENV
  send-e2e-results:
    steps:
      - slack/notify:
          channel: ci-notif
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*:test_tube: E2E reports have been generated*\n*<${CIRCLE_BUILD_URL}|CircleCI Job #${CIRCLE_BUILD_NUM}>*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${STATUS_MESSAGE}*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job ID :*\n ${CIRCLE_JOB}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build Number :*\n ${CIRCLE_BUILD_NUM}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Test results*"
                  },
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Passed :*\n ${PASSED_TESTS:-0}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed :*\n ${FAILED_TESTS:-0}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Flaky :*\n ${FLAKY_TESTS:-0}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Skipped :*\n ${SKIPPED_TESTS:-0}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "style": "primary",
                      "text": {
                        "type": "plain_text",
                        "text": "View report",
                        "emoji": true
                      },
                      "url": "https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/playwright-report/index.html",
                      "action_id": "view_reports"
                    }
                  ]
                }
              ]
            }

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - e2e_test
  extract-e2e-results:
    docker:
      - image: circleci/node:latest
    steps:
      - extract-e2e-results
  send-e2e-results:
    docker:
      - image: circleci/node:latest
    steps:
      - send-e2e-results
