version: 2.1

orbs:
  slack: circleci/slack@4.9.3

workflows:
  test-deploy:
    jobs:
      - test
      - notify-e2e-fail:
          requires:
            - test
          context:
            - slack-ci
      - notify-e2e-pass:
          requires:
            - test
          context:
            - slack-ci
  genereate-e2e-report:
    triggers:
      - schedule:
          cron: "23 8 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test

commands:
  e2e_test:
    steps:
      - checkout
      # - run:
      #     working_directory: crx/src
      #     name: Install crx deps
      #     command: npm install
      # - run:
      #     working_directory: crx/src
      #     name: Prepare crx
      #     command: npm run prod
      - run:
          working_directory: e2e
          name: Install dependencies
          command: npm install
      - run:
          working_directory: e2e
          name: Setup playwright
          command: npx playwright install
      - run:
          working_directory: e2e
          name: Run e2e
          command: npx playwright test
      - store_artifacts:
          path: e2e/playwright-report
          destination: playwright-test-results
       - run:
          name: Save Artifact URL
          command: echo "export E2E_ARTIFACT_URL=https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/playwright-test-results/index.html"

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - e2e_test
  notify-e2e-fail:
    docker:
      - image: circleci/node:16
    steps:
      - slack/notify:
          event: fail
          custom: |
            {
              "attachments": [
                {
                  "color": "danger",
                  "text": "Job failed. Check the test results.",
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Test Results",
                      "url": $E2E_ARTIFACT_URL
                    }
                  ]
                }
              ]
            }
  notify-e2e-pass:
    docker:
      - image: circleci/node:16
    steps:
      - slack/notify:
          event: pass
          custom: |
            {
              "attachments": [
                {
                  "color": "good",
                  "text": "Job passed. Check the test results.",
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Test Results",
                      "url": $E2E_ARTIFACT_URL
                    }
                  ]
                }
              ]
            }
