version: 2.1
workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - checkout
      - run:
          working_directory: e2e
          name: Install dependencies
          command: npm install
      - run:
          working_directory: e2e
          name: Setup playwright
          command: npx playwright install
      - run:
          working_directory: e2e
          name: Run e2e
          command: npx playwright test
