version: 2.1
workflows:
  test-deploy:
    jobs:
      - test
  genereate-e2e-report:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
commands:
  e2e_test:
    steps:
      - checkout
      # - run:
      #     working_directory: crx/src
      #     name: Install crx deps
      #     command: npm install
      # - run:
      #     working_directory: crx/src
      #     name: Prepare crx
      #     command: npm run prod
      - run:
          working_directory: e2e
          name: Install dependencies
          command: npm install
      - run:
          working_directory: e2e
          name: Setup playwright
          command: npx playwright install
      - run:
          working_directory: e2e
          name: Run e2e
          command: npx playwright test
      - store_artifacts:
          path: e2e/playwright-report
          destination: playwright-test-results

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - e2e_test
