version: 2.1

orbs:
  slack: circleci/slack@4.9.3

workflows:
  test-deploy:
    jobs:
      - test:
          context:
            - slack-ci
  genereate-e2e-report:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
commands:
  e2e_test:
    steps:
      - checkout
      # - run:
      #     working_directory: crx/src
      #     name: Install crx deps
      #     command: npm install
      # - run:
      #     working_directory: crx/src
      #     name: Prepare crx
      #     command: npm run prod
      - run:
          working_directory: e2e
          name: Install dependencies
          command: npm install
      - run:
          working_directory: e2e
          name: Setup playwright
          command: npx playwright install
      - run:
          working_directory: e2e
          name: Run e2e
          command: npx playwright test
      - store_artifacts:
          path: e2e/playwright-report
          destination: playwright-test-results
      - slack/notify:
          event: fail
          template: basic_fail_1
          custom: |
            {
              "text": "${CIRCLE_BRANCH}: ${CIRCLE_JOB} failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":x: ${CIRCLE_BRANCH}: ${CIRCLE_JOB} failed",
                    "emoji": true
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View report"
                      },
                      "url": "https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/playwright-test-results/index.html"
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          event: pass
          template: basic_success_1
          custom: |
            {
              "text": "${CIRCLE_BRANCH}: ${CIRCLE_JOB} passed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rocket: ${CIRCLE_BRANCH}: ${CIRCLE_JOB} passed",
                    "emoji": true
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View report"
                      },
                      "url": "https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/playwright-test-results/index.html"
                    }
                  ]
                }
              ]
            }

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - e2e_test
