version: 2.1
workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          working_directory: e2e
          name: Install dependencies
          command: npm install
      - run:
          working_directory: e2e
          name: Run e2e
          command: npx playwright test
